services:

  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
      args:
        BUILD_ENV: Debug
    volumes:
      - ./backend/WebAPI/appsettings.Development.json:/app/appsettings.Development.json:ro
    depends_on:
      - Five68-db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: Europe/Rome
  db_init:
    hostname: db_init
    profiles: [ init ]
    build:
      context: backend/
      dockerfile: Five68Initializer/Dockerfile
    depends_on:
      - Five68-db

  # Database
  Five68-db:
    hostname: Five68-db
    container_name: Five68-postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Five68-db"
    ports:
      - "5432:5432"
    volumes:
      - ./io/database:/var/lib/postgresql/data
